# Generated by Django 2.2.5 on 2019-09-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
